SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  SELECT * FROM DGM.DIM_DQAXIS;
--
Insert into DIM_DQAXIS
   (DQX_PK, DQX_STATUS, DQX_DATETIME_LOAD, DQX_NAME, DQX_FUNCKEY, 
    DQX_WEIGHT)
 Values
   (2, NULL, TO_TIMESTAMP('26/01/2017 08:29:11.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'Completness', 'COMPL', 
    6);
Insert into DIM_DQAXIS
   (DQX_PK, DQX_STATUS, DQX_DATETIME_LOAD, DQX_NAME, DQX_FUNCKEY, 
    DQX_WEIGHT)
 Values
   (3, NULL, TO_TIMESTAMP('26/01/2017 08:29:11.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'Timeless', 'TIME', 
    1);
Insert into DIM_DQAXIS
   (DQX_PK, DQX_STATUS, DQX_DATETIME_LOAD, DQX_NAME, DQX_FUNCKEY, 
    DQX_WEIGHT)
 Values
   (4, NULL, TO_TIMESTAMP('26/01/2017 08:29:11.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'Precision', 'PREC', 
    1);
Insert into DIM_DQAXIS
   (DQX_PK, DQX_STATUS, DQX_DATETIME_LOAD, DQX_NAME, DQX_FUNCKEY, 
    DQX_WEIGHT)
 Values
   (0, NULL, TO_TIMESTAMP('02/12/2016 02:23:49.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'Unknown', 'UNKN', 
    1);
Insert into DIM_DQAXIS
   (DQX_PK, DQX_STATUS, DQX_DATETIME_LOAD, DQX_NAME, DQX_FUNCKEY, 
    DQX_WEIGHT)
 Values
   (1, NULL, TO_TIMESTAMP('26/01/2017 08:29:11.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'Accuracy', 'ACCY', 
    2);
Insert into DIM_DQAXIS
   (DQX_PK, DQX_STATUS, DQX_DATETIME_LOAD, DQX_NAME, DQX_FUNCKEY, 
    DQX_WEIGHT)
 Values
   (5, NULL, TO_TIMESTAMP('26/01/2017 08:29:11.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'Integrity', 'INTEG', 
    3);
COMMIT;
