SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  SELECT * FROM DGM.DIM_DATASOURCE;
--
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (2, 'Hermes_Inc', 'HIN_Merged_Individual', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'HIN_Merged_Individual');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (3, 'DemoWEmbley', 'C_B_PARTY_ELECT_ADDR1', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'C_B_PARTY_ELECT_ADDR1');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (4, 'DemoWEmbley', 'C_B_PARTY_ADDRESS1', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'C_B_PARTY_ADDRESS1');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (5, 'DemoWEmbley', 'C_B_PARTY1', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'C_B_PARTY1');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (6, 'DemoWEmbley', 'C_B_PARTY_ELECT_ADDR', TO_TIMESTAMP('26/01/2017 08:29:15.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'C_B_PARTY_ELECT_ADDR');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (7, NULL, 'Contract1', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'Contract1');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (8, NULL, 'HIN_Drivers', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'HIN_Drivers');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (9, NULL, 'HIN_CRM_Insured_Drivers', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'HIN_CRM_Insured_Drivers');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (10, NULL, 'HIN_Insured', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'HIN_Insured');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (11, 'DemoWEmbley', 'C_B_PARTY', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'C_B_PARTY');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (12, 'DemoWEmbley', 'C_B_PARTY_ADDRESS', TO_TIMESTAMP('26/01/2017 08:29:15.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'C_B_PARTY_ADDRESS');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (13, NULL, 'Exp_Clients1', TO_TIMESTAMP('26/01/2017 08:29:15.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'Exp_Clients1');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (14, 'DemoWEmbley', 'C_B_PARTY_TELECOM1', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'C_B_PARTY_TELECOM1');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (15, 'BCBS', 'STG_PARTY1', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'STG_PARTY1');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (16, 'DemoWEmbley', 'C_B_PARTY_TELECOM', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'C_B_PARTY_TELECOM');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (0, 'Unknown', 'Unknown', TO_TIMESTAMP('02/12/2016 02:23:49.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'UNKN');
Insert into DIM_DATASOURCE
   (DSO_PK, DSO_CONNECTION, DSO_SOURCENAME, DSO_DATETIME_LOAD, DSO_FUNCKEY)
 Values
   (1, NULL, 'HIN_CRM', TO_TIMESTAMP('26/01/2017 08:29:16.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'HIN_CRM');
COMMIT;
