SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  SELECT * FROM DGM.LND_TERM_RELATIONSHIPS;
--
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0cs5BEeWu4gbligZhTg|U:yQQNHM5BEeWu4gbligZhTg', 'U:yPh0cs5BEeWu4gbligZhTg', 'U:yQQNHM5BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0c85BEeWu4gbligZhTg|U:yQQ0Oc5BEeWu4gbligZhTg', 'U:yPh0c85BEeWu4gbligZhTg', 'U:yQQ0Oc5BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0d85BEeWu4gbligZhTg|U:yQQNHM5BEeWu4gbligZhTg', 'U:yPh0d85BEeWu4gbligZhTg', 'U:yQQNHM5BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0d85BEeWu4gbligZhTg|U:yPibqs5BEeWu4gbligZhTg', 'U:yPh0d85BEeWu4gbligZhTg', 'U:yPibqs5BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0ec5BEeWu4gbligZhTg|U:yQQNHM5BEeWu4gbligZhTg', 'U:yPh0ec5BEeWu4gbligZhTg', 'U:yQQNHM5BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('not_same_as|U:yPh0es5BEeWu4gbligZhTg|U:yPh0hM5BEeWu4gbligZhTg', 'U:yPh0es5BEeWu4gbligZhTg', 'U:yPh0hM5BEeWu4gbligZhTg', 'not_same_as', 'not_same_as', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yPh0es5BEeWu4gbligZhTg|U:yPh0g85BEeWu4gbligZhTg', 'U:yPh0es5BEeWu4gbligZhTg', 'U:yPh0g85BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('not_same_as|U:yPh0e85BEeWu4gbligZhTg|U:yPh0l85BEeWu4gbligZhTg', 'U:yPh0e85BEeWu4gbligZhTg', 'U:yPh0l85BEeWu4gbligZhTg', 'not_same_as', 'not_same_as', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0e85BEeWu4gbligZhTg|U:yQQNHM5BEeWu4gbligZhTg', 'U:yPh0e85BEeWu4gbligZhTg', 'U:yQQNHM5BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yPh0fM5BEeWu4gbligZhTg|U:yPh0is5BEeWu4gbligZhTg', 'U:yPh0fM5BEeWu4gbligZhTg', 'U:yPh0is5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0fs5BEeWu4gbligZhTg|U:yPh0c85BEeWu4gbligZhTg', 'U:yPh0fs5BEeWu4gbligZhTg', 'U:yPh0c85BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0fs5BEeWu4gbligZhTg|U:yPh0i85BEeWu4gbligZhTg', 'U:yPh0fs5BEeWu4gbligZhTg', 'U:yPh0i85BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('not_same_as|U:yPh0f85BEeWu4gbligZhTg|U:yPh0eM5BEeWu4gbligZhTg', 'U:yPh0f85BEeWu4gbligZhTg', 'U:yPh0eM5BEeWu4gbligZhTg', 'not_same_as', 'not_same_as', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('not_same_as|U:yPh0hM5BEeWu4gbligZhTg|U:yPh0es5BEeWu4gbligZhTg', 'U:yPh0hM5BEeWu4gbligZhTg', 'U:yPh0es5BEeWu4gbligZhTg', 'not_same_as', 'not_same_as', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yPh0hM5BEeWu4gbligZhTg|U:yPh0g85BEeWu4gbligZhTg', 'U:yPh0hM5BEeWu4gbligZhTg', 'U:yPh0g85BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('see_also|U:yPh0h85BEeWu4gbligZhTg|U:yPh0kc5BEeWu4gbligZhTg', 'U:yPh0h85BEeWu4gbligZhTg', 'U:yPh0kc5BEeWu4gbligZhTg', 'see_also', 'see_also', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0iM5BEeWu4gbligZhTg|U:yQQNHM5BEeWu4gbligZhTg', 'U:yPh0iM5BEeWu4gbligZhTg', 'U:yQQNHM5BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Sets out|U:yPh0ic5BEeWu4gbligZhTg|U:yPh0es5BEeWu4gbligZhTg', 'U:yPh0ic5BEeWu4gbligZhTg', 'U:yPh0es5BEeWu4gbligZhTg', 'Sets out', 'Sets out', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Sets out|U:yPh0ic5BEeWu4gbligZhTg|U:yPh0hM5BEeWu4gbligZhTg', 'U:yPh0ic5BEeWu4gbligZhTg', 'U:yPh0hM5BEeWu4gbligZhTg', 'Sets out', 'Sets out', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('not_same_as|U:yPh0is5BEeWu4gbligZhTg|U:yPh0fM5BEeWu4gbligZhTg', 'U:yPh0is5BEeWu4gbligZhTg', 'U:yPh0fM5BEeWu4gbligZhTg', 'not_same_as', 'not_same_as', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Authorized under|U:yPh0i85BEeWu4gbligZhTg|U:yPh0fs5BEeWu4gbligZhTg', 'U:yPh0i85BEeWu4gbligZhTg', 'U:yPh0fs5BEeWu4gbligZhTg', 'Authorized under', 'Authorized under', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0i85BEeWu4gbligZhTg|U:yPh0c85BEeWu4gbligZhTg', 'U:yPh0i85BEeWu4gbligZhTg', 'U:yPh0c85BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('see_also|U:yPh0i85BEeWu4gbligZhTg|U:yPh0fs5BEeWu4gbligZhTg', 'U:yPh0i85BEeWu4gbligZhTg', 'U:yPh0fs5BEeWu4gbligZhTg', 'see_also', 'see_also', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yPh0js5BEeWu4gbligZhTg|U:yQQ0Qc5BEeWu4gbligZhTg', 'U:yPh0js5BEeWu4gbligZhTg', 'U:yQQ0Qc5BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('not_same_as|U:yPh0j85BEeWu4gbligZhTg|U:yPibqs5BEeWu4gbligZhTg', 'U:yPh0j85BEeWu4gbligZhTg', 'U:yPibqs5BEeWu4gbligZhTg', 'not_same_as', 'not_same_as', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('related|U:yPh0kM5BEeWu4gbligZhTg|U:yQQNHM5BEeWu4gbligZhTg', 'U:yPh0kM5BEeWu4gbligZhTg', 'U:yQQNHM5BEeWu4gbligZhTg', 'related', 'related', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('not_same_as|U:yPh0kc5BEeWu4gbligZhTg|U:yPh0iM5BEeWu4gbligZhTg', 'U:yPh0kc5BEeWu4gbligZhTg', 'U:yPh0iM5BEeWu4gbligZhTg', 'not_same_as', 'not_same_as', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('not_same_as|U:yPh0ls5BEeWu4gbligZhTg|U:yPh0hc5BEeWu4gbligZhTg', 'U:yPh0ls5BEeWu4gbligZhTg', 'U:yPh0hc5BEeWu4gbligZhTg', 'not_same_as', 'not_same_as', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Is A|U:yPibqs5BEeWu4gbligZhTg|U:yQQNHM5BEeWu4gbligZhTg', 'U:yPibqs5BEeWu4gbligZhTg', 'U:yQQNHM5BEeWu4gbligZhTg', 'Is A', 'Is A', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0c85BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0c85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0h85BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0h85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0f85BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0f85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0ds5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0ds5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yQQ0Oc5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yQQ0Oc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0lc5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0lc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPibrs5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPibrs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yQQ0PM5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yQQ0PM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0eM5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0eM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0fM5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0fM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0kc5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0kc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0g85BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0g85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0is5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0is5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0ic5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0ic5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yQQNJM5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yQQNJM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0dc5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0dc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0jM5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0jM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0hs5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0hs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFc5BEeWu4gbligZhTg|U:yPh0fs5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'U:yPh0fs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yQQNJM5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yQQNJM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yQQ0PM5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yQQ0PM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0h85BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0h85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0hs5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0hs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0is5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0is5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0g85BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0g85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0jM5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0jM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0fM5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0fM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0f85BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0f85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPibrs5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPibrs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0ds5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0ds5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yQQ0Oc5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yQQ0Oc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0lc5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0lc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0dc5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0dc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0eM5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0eM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0c85BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0c85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0ic5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0ic5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0kc5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0kc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNFs5BEeWu4gbligZhTg|U:yPh0fs5BEeWu4gbligZhTg', 'U:yQQNFs5BEeWu4gbligZhTg', 'U:yPh0fs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yQQNGM5BEeWu4gbligZhTg|U:yQQ0Q85BEeWu4gbligZhTg', 'U:yQQNGM5BEeWu4gbligZhTg', 'U:yQQ0Q85BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('see_also|U:yQQNGM5BEeWu4gbligZhTg|U:yQQ0Os5BEeWu4gbligZhTg', 'U:yQQNGM5BEeWu4gbligZhTg', 'U:yQQ0Os5BEeWu4gbligZhTg', 'see_also', 'see_also', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNHM5BEeWu4gbligZhTg|U:yPh0ec5BEeWu4gbligZhTg', 'U:yQQNHM5BEeWu4gbligZhTg', 'U:yPh0ec5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQNHc5BEeWu4gbligZhTg|U:yPh0ec5BEeWu4gbligZhTg', 'U:yQQNHc5BEeWu4gbligZhTg', 'U:yPh0ec5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Mastered In|U:yQQNIM5BEeWu4gbligZhTg|U:yRT9XM5BEeWu4gbligZhTg', 'U:yQQNIM5BEeWu4gbligZhTg', 'U:yRT9XM5BEeWu4gbligZhTg', 'Mastered In', 'Mastered In', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yQQNIM5BEeWu4gbligZhTg|U:yQQ0OM5BEeWu4gbligZhTg', 'U:yQQNIM5BEeWu4gbligZhTg', 'U:yQQ0OM5BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yQQNIM5BEeWu4gbligZhTg|U:yQQ0Rc5BEeWu4gbligZhTg', 'U:yQQNIM5BEeWu4gbligZhTg', 'U:yQQ0Rc5BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yQQNIc5BEeWu4gbligZhTg|U:yQQ0Qc5BEeWu4gbligZhTg', 'U:yQQNIc5BEeWu4gbligZhTg', 'U:yQQ0Qc5BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yQQNI85BEeWu4gbligZhTg|U:yQQ0OM5BEeWu4gbligZhTg', 'U:yQQNI85BEeWu4gbligZhTg', 'U:yQQ0OM5BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yQQNJc5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yQQNJc5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yQQNJs5BEeWu4gbligZhTg|U:yQQ0Q85BEeWu4gbligZhTg', 'U:yQQNJs5BEeWu4gbligZhTg', 'U:yQQ0Q85BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('see_also|U:yQQNJs5BEeWu4gbligZhTg|U:yQQNGM5BEeWu4gbligZhTg', 'U:yQQNJs5BEeWu4gbligZhTg', 'U:yQQNGM5BEeWu4gbligZhTg', 'see_also', 'see_also', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('see_also|U:yQQNJs5BEeWu4gbligZhTg|U:yQQ0Os5BEeWu4gbligZhTg', 'U:yQQNJs5BEeWu4gbligZhTg', 'U:yQQ0Os5BEeWu4gbligZhTg', 'see_also', 'see_also', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Authorized under|U:yQQ0Oc5BEeWu4gbligZhTg|U:yPh0fs5BEeWu4gbligZhTg', 'U:yQQ0Oc5BEeWu4gbligZhTg', 'U:yPh0fs5BEeWu4gbligZhTg', 'Authorized under', 'Authorized under', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yQQ0Os5BEeWu4gbligZhTg|U:yQQ0Q85BEeWu4gbligZhTg', 'U:yQQ0Os5BEeWu4gbligZhTg', 'U:yQQ0Q85BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('not_same_as|U:yQQ0PM5BEeWu4gbligZhTg|U:yPh0ds5BEeWu4gbligZhTg', 'U:yQQ0PM5BEeWu4gbligZhTg', 'U:yPh0ds5BEeWu4gbligZhTg', 'not_same_as', 'not_same_as', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('see_also|U:yQQ0PM5BEeWu4gbligZhTg|U:yPh0ds5BEeWu4gbligZhTg', 'U:yQQ0PM5BEeWu4gbligZhTg', 'U:yPh0ds5BEeWu4gbligZhTg', 'see_also', 'see_also', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yQQ0Ps5BEeWu4gbligZhTg|U:yQQ0Qc5BEeWu4gbligZhTg', 'U:yQQ0Ps5BEeWu4gbligZhTg', 'U:yQQ0Qc5BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yQQ0P85BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yQQ0P85BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Mastered In|U:yQQ0Qs5BEeWu4gbligZhTg|U:yRT9YM5BEeWu4gbligZhTg', 'U:yQQ0Qs5BEeWu4gbligZhTg', 'U:yRT9YM5BEeWu4gbligZhTg', 'Mastered In', 'Mastered In', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('calculatedFrom|U:yQQ0Qs5BEeWu4gbligZhTg|U:yQQNF85BEeWu4gbligZhTg', 'U:yQQ0Qs5BEeWu4gbligZhTg', 'U:yQQNF85BEeWu4gbligZhTg', 'calculatedFrom', 'calculatedFrom', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('calculatedFrom|U:yQQ0Rs5BEeWu4gbligZhTg|U:yQQ0P85BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yQQ0P85BEeWu4gbligZhTg', 'calculatedFrom', 'calculatedFrom', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('calculatedFrom|U:yQQ0Rs5BEeWu4gbligZhTg|U:yQQNEs5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yQQNEs5BEeWu4gbligZhTg', 'calculatedFrom', 'calculatedFrom', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('calculatedFrom|U:yQQ0Rs5BEeWu4gbligZhTg|U:yQQNFc5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'calculatedFrom', 'calculatedFrom', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQ0Rs5BEeWu4gbligZhTg|U:yQQ0Oc5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yQQ0Oc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQ0Rs5BEeWu4gbligZhTg|U:yQQNIc5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yQQNIc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQ0Rs5BEeWu4gbligZhTg|U:yQQ0Ps5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yQQ0Ps5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQ0Rs5BEeWu4gbligZhTg|U:yPh0mc5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yPh0mc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQ0Rs5BEeWu4gbligZhTg|U:yQQ0RM5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yQQ0RM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yQQ0Rs5BEeWu4gbligZhTg|U:yPh0c85BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yPh0c85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('governedBy|U:yQQ0Rs5BEeWu4gbligZhTg|U:yRuMX85BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRuMX85BEeWu4gbligZhTg', 'governedBy', 'governedBy', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXB85BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXB85BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXB85BEeWu4gbligZhTg|U:yQQNF85BEeWu4gbligZhTg', 'U:yRIXB85BEeWu4gbligZhTg', 'U:yQQNF85BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXB85BEeWu4gbligZhTg|U:yRT9YM5BEeWu4gbligZhTg', 'U:yRIXB85BEeWu4gbligZhTg', 'U:yRT9YM5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXCM5BEeWu4gbligZhTg|U:yRT9Vc5BEeWu4gbligZhTg', 'U:yRIXCM5BEeWu4gbligZhTg', 'U:yRT9Vc5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXCM5BEeWu4gbligZhTg|U:yQQNH85BEeWu4gbligZhTg', 'U:yRIXCM5BEeWu4gbligZhTg', 'U:yQQNH85BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXCM5BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXCM5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXCc5BEeWu4gbligZhTg|U:yRT9Vc5BEeWu4gbligZhTg', 'U:yRIXCc5BEeWu4gbligZhTg', 'U:yRT9Vc5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXCc5BEeWu4gbligZhTg|U:yQQNI85BEeWu4gbligZhTg', 'U:yRIXCc5BEeWu4gbligZhTg', 'U:yQQNI85BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXCc5BEeWu4gbligZhTg|U:yRT9VM5BEeWu4gbligZhTg', 'U:yRIXCc5BEeWu4gbligZhTg', 'U:yRT9VM5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Entity|U:yRIXCc5BEeWu4gbligZhTg|U:yQQ0OM5BEeWu4gbligZhTg', 'U:yRIXCc5BEeWu4gbligZhTg', 'U:yQQ0OM5BEeWu4gbligZhTg', 'Target Entity', 'Target Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXCs5BEeWu4gbligZhTg|U:yRT9Wc5BEeWu4gbligZhTg', 'U:yRIXCs5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXCs5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRIXCs5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXCs5BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXCs5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXC85BEeWu4gbligZhTg|U:yRT9W85BEeWu4gbligZhTg', 'U:yRIXC85BEeWu4gbligZhTg', 'U:yRT9W85BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXC85BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRIXC85BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXC85BEeWu4gbligZhTg|U:yRT9Wc5BEeWu4gbligZhTg', 'U:yRIXC85BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXDM5BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXDM5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXDM5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRIXDM5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXDM5BEeWu4gbligZhTg|U:yRT9V85BEeWu4gbligZhTg', 'U:yRIXDM5BEeWu4gbligZhTg', 'U:yRT9V85BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXDc5BEeWu4gbligZhTg|U:yRT9Wc5BEeWu4gbligZhTg', 'U:yRIXDc5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXDc5BEeWu4gbligZhTg|U:yQQNFc5BEeWu4gbligZhTg', 'U:yRIXDc5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXDc5BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXDc5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Entity|U:yRIXDc5BEeWu4gbligZhTg|U:yQQNG85BEeWu4gbligZhTg', 'U:yRIXDc5BEeWu4gbligZhTg', 'U:yQQNG85BEeWu4gbligZhTg', 'Target Entity', 'Target Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXDs5BEeWu4gbligZhTg|U:yRT9XM5BEeWu4gbligZhTg', 'U:yRIXDs5BEeWu4gbligZhTg', 'U:yRT9XM5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXDs5BEeWu4gbligZhTg|U:yQQNIM5BEeWu4gbligZhTg', 'U:yRIXDs5BEeWu4gbligZhTg', 'U:yQQNIM5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXDs5BEeWu4gbligZhTg|U:yRT9Wc5BEeWu4gbligZhTg', 'U:yRIXDs5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXD85BEeWu4gbligZhTg|U:yRT9Vc5BEeWu4gbligZhTg', 'U:yRIXD85BEeWu4gbligZhTg', 'U:yRT9Vc5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXD85BEeWu4gbligZhTg|U:yQQ0Rc5BEeWu4gbligZhTg', 'U:yRIXD85BEeWu4gbligZhTg', 'U:yQQ0Rc5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXD85BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXD85BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXEM5BEeWu4gbligZhTg|U:yRT9Xs5BEeWu4gbligZhTg', 'U:yRIXEM5BEeWu4gbligZhTg', 'U:yRT9Xs5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXEM5BEeWu4gbligZhTg|U:yQQ0OM5BEeWu4gbligZhTg', 'U:yRIXEM5BEeWu4gbligZhTg', 'U:yQQ0OM5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXEM5BEeWu4gbligZhTg|U:yRT9VM5BEeWu4gbligZhTg', 'U:yRIXEM5BEeWu4gbligZhTg', 'U:yRT9VM5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXEc5BEeWu4gbligZhTg|U:yRT9VM5BEeWu4gbligZhTg', 'U:yRIXEc5BEeWu4gbligZhTg', 'U:yRT9VM5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXEc5BEeWu4gbligZhTg|U:yQQ0OM5BEeWu4gbligZhTg', 'U:yRIXEc5BEeWu4gbligZhTg', 'U:yQQ0OM5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXEc5BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXEc5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXEs5BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXEs5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXEs5BEeWu4gbligZhTg|U:yQQ0OM5BEeWu4gbligZhTg', 'U:yRIXEs5BEeWu4gbligZhTg', 'U:yQQ0OM5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Entity|U:yRIXEs5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRIXEs5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'Target Entity', 'Target Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXE85BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXE85BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXE85BEeWu4gbligZhTg|U:yQQ0Rc5BEeWu4gbligZhTg', 'U:yRIXE85BEeWu4gbligZhTg', 'U:yQQ0Rc5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Entity|U:yRIXE85BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRIXE85BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'Target Entity', 'Target Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXFM5BEeWu4gbligZhTg|U:yRT9YM5BEeWu4gbligZhTg', 'U:yRIXFM5BEeWu4gbligZhTg', 'U:yRT9YM5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXFM5BEeWu4gbligZhTg|U:yQQ0Qs5BEeWu4gbligZhTg', 'U:yRIXFM5BEeWu4gbligZhTg', 'U:yQQ0Qs5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXFM5BEeWu4gbligZhTg|U:yRT9V85BEeWu4gbligZhTg', 'U:yRIXFM5BEeWu4gbligZhTg', 'U:yRT9V85BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Entity|U:yRIXFM5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRIXFM5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'Target Entity', 'Target Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXFc5BEeWu4gbligZhTg|U:yRT9Vc5BEeWu4gbligZhTg', 'U:yRIXFc5BEeWu4gbligZhTg', 'U:yRT9Vc5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXFc5BEeWu4gbligZhTg|U:yQQ0Rc5BEeWu4gbligZhTg', 'U:yRIXFc5BEeWu4gbligZhTg', 'U:yQQ0Rc5BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXFc5BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXFc5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Application|U:yRIXFs5BEeWu4gbligZhTg|U:yRT9Wc5BEeWu4gbligZhTg', 'U:yRIXFs5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'Source Application', 'Source Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Source Entity|U:yRIXFs5BEeWu4gbligZhTg|U:yQQNF85BEeWu4gbligZhTg', 'U:yRIXFs5BEeWu4gbligZhTg', 'U:yQQNF85BEeWu4gbligZhTg', 'Source Entity', 'Source Entity', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Target Application|U:yRIXFs5BEeWu4gbligZhTg|U:yRT9YM5BEeWu4gbligZhTg', 'U:yRIXFs5BEeWu4gbligZhTg', 'U:yRT9YM5BEeWu4gbligZhTg', 'Target Application', 'Target Application', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9VM5BEeWu4gbligZhTg|U:yRIXEc5BEeWu4gbligZhTg', 'U:yRT9VM5BEeWu4gbligZhTg', 'U:yRIXEc5BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9VM5BEeWu4gbligZhTg|U:yQQNG85BEeWu4gbligZhTg', 'U:yRT9VM5BEeWu4gbligZhTg', 'U:yQQNG85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9VM5BEeWu4gbligZhTg|U:yQQ0OM5BEeWu4gbligZhTg', 'U:yRT9VM5BEeWu4gbligZhTg', 'U:yQQ0OM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9Vc5BEeWu4gbligZhTg|U:yRIXCc5BEeWu4gbligZhTg', 'U:yRT9Vc5BEeWu4gbligZhTg', 'U:yRIXCc5BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vc5BEeWu4gbligZhTg|U:yQQ0Rc5BEeWu4gbligZhTg', 'U:yRT9Vc5BEeWu4gbligZhTg', 'U:yQQ0Rc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vc5BEeWu4gbligZhTg|U:yQQNH85BEeWu4gbligZhTg', 'U:yRT9Vc5BEeWu4gbligZhTg', 'U:yQQNH85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vc5BEeWu4gbligZhTg|U:yQQNI85BEeWu4gbligZhTg', 'U:yRT9Vc5BEeWu4gbligZhTg', 'U:yQQNI85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vc5BEeWu4gbligZhTg|U:yQQ0OM5BEeWu4gbligZhTg', 'U:yRT9Vc5BEeWu4gbligZhTg', 'U:yQQ0OM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vs5BEeWu4gbligZhTg|U:yPh0mc5BEeWu4gbligZhTg', 'U:yRT9Vs5BEeWu4gbligZhTg', 'U:yPh0mc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vs5BEeWu4gbligZhTg|U:yQQNEs5BEeWu4gbligZhTg', 'U:yRT9Vs5BEeWu4gbligZhTg', 'U:yQQNEs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vs5BEeWu4gbligZhTg|U:yQQNIc5BEeWu4gbligZhTg', 'U:yRT9Vs5BEeWu4gbligZhTg', 'U:yQQNIc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vs5BEeWu4gbligZhTg|U:yQQ0Ps5BEeWu4gbligZhTg', 'U:yRT9Vs5BEeWu4gbligZhTg', 'U:yQQ0Ps5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vs5BEeWu4gbligZhTg|U:yQQ0Qs5BEeWu4gbligZhTg', 'U:yRT9Vs5BEeWu4gbligZhTg', 'U:yQQ0Qs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vs5BEeWu4gbligZhTg|U:yQQ0Rc5BEeWu4gbligZhTg', 'U:yRT9Vs5BEeWu4gbligZhTg', 'U:yQQ0Rc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vs5BEeWu4gbligZhTg|U:yPh0fc5BEeWu4gbligZhTg', 'U:yRT9Vs5BEeWu4gbligZhTg', 'U:yPh0fc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Vs5BEeWu4gbligZhTg|U:yQQNGc5BEeWu4gbligZhTg', 'U:yRT9Vs5BEeWu4gbligZhTg', 'U:yQQNGc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9V85BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRT9V85BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9V85BEeWu4gbligZhTg|U:yPh0c85BEeWu4gbligZhTg', 'U:yRT9V85BEeWu4gbligZhTg', 'U:yPh0c85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9WM5BEeWu4gbligZhTg|U:yRIXDM5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXDM5BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9WM5BEeWu4gbligZhTg|U:yRIXB85BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXB85BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9WM5BEeWu4gbligZhTg|U:yRIXEs5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXEs5BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9WM5BEeWu4gbligZhTg|U:yRIXE85BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'U:yRIXE85BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9WM5BEeWu4gbligZhTg|U:yQQNH85BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'U:yQQNH85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9WM5BEeWu4gbligZhTg|U:yQQ0Rc5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'U:yQQ0Rc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9WM5BEeWu4gbligZhTg|U:yQQNF85BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'U:yQQNF85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9WM5BEeWu4gbligZhTg|U:yQQNG85BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'U:yQQNG85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9WM5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9Wc5BEeWu4gbligZhTg|U:yRIXFs5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'U:yRIXFs5BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9Wc5BEeWu4gbligZhTg|U:yRIXCs5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'U:yRIXCs5BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9Wc5BEeWu4gbligZhTg|U:yRIXDc5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'U:yRIXDc5BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Wc5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Wc5BEeWu4gbligZhTg|U:yQQNFc5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Wc5BEeWu4gbligZhTg|U:yQQNF85BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'U:yQQNF85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Wc5BEeWu4gbligZhTg|U:yQQ0OM5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'U:yQQ0OM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Wc5BEeWu4gbligZhTg|U:yQQNIM5BEeWu4gbligZhTg', 'U:yRT9Wc5BEeWu4gbligZhTg', 'U:yQQNIM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9Ws5BEeWu4gbligZhTg|U:yRIXC85BEeWu4gbligZhTg', 'U:yRT9Ws5BEeWu4gbligZhTg', 'U:yRIXC85BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Ws5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRT9Ws5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9W85BEeWu4gbligZhTg|U:yRIXC85BEeWu4gbligZhTg', 'U:yRT9W85BEeWu4gbligZhTg', 'U:yRIXC85BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9W85BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRT9W85BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Authorized under|U:yRT9XM5BEeWu4gbligZhTg|U:yRIXDs5BEeWu4gbligZhTg', 'U:yRT9XM5BEeWu4gbligZhTg', 'U:yRIXDs5BEeWu4gbligZhTg', 'Authorized under', 'Authorized under', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9XM5BEeWu4gbligZhTg|U:yQQNHM5BEeWu4gbligZhTg', 'U:yRT9XM5BEeWu4gbligZhTg', 'U:yQQNHM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9XM5BEeWu4gbligZhTg|U:yQQNFc5BEeWu4gbligZhTg', 'U:yRT9XM5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9XM5BEeWu4gbligZhTg|U:yQQNIM5BEeWu4gbligZhTg', 'U:yRT9XM5BEeWu4gbligZhTg', 'U:yQQNIM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9Xc5BEeWu4gbligZhTg|U:yRIXEM5BEeWu4gbligZhTg', 'U:yRT9Xc5BEeWu4gbligZhTg', 'U:yRIXEM5BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Xc5BEeWu4gbligZhTg|U:yQQ0Rc5BEeWu4gbligZhTg', 'U:yRT9Xc5BEeWu4gbligZhTg', 'U:yQQ0Rc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Xc5BEeWu4gbligZhTg|U:yQQNH85BEeWu4gbligZhTg', 'U:yRT9Xc5BEeWu4gbligZhTg', 'U:yQQNH85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Xc5BEeWu4gbligZhTg|U:yQQNEs5BEeWu4gbligZhTg', 'U:yRT9Xc5BEeWu4gbligZhTg', 'U:yQQNEs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Xc5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRT9Xc5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Xc5BEeWu4gbligZhTg|U:yQQNI85BEeWu4gbligZhTg', 'U:yRT9Xc5BEeWu4gbligZhTg', 'U:yQQNI85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9Xc5BEeWu4gbligZhTg|U:yQQ0OM5BEeWu4gbligZhTg', 'U:yRT9Xc5BEeWu4gbligZhTg', 'U:yQQ0OM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9X85BEeWu4gbligZhTg|U:yQQNH85BEeWu4gbligZhTg', 'U:yRT9X85BEeWu4gbligZhTg', 'U:yQQNH85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9X85BEeWu4gbligZhTg|U:yQQNHM5BEeWu4gbligZhTg', 'U:yRT9X85BEeWu4gbligZhTg', 'U:yQQNHM5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9X85BEeWu4gbligZhTg|U:yQQNFc5BEeWu4gbligZhTg', 'U:yRT9X85BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9X85BEeWu4gbligZhTg|U:yQQ0Rc5BEeWu4gbligZhTg', 'U:yRT9X85BEeWu4gbligZhTg', 'U:yQQ0Rc5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Data Flow|U:yRT9YM5BEeWu4gbligZhTg|U:yRIXFM5BEeWu4gbligZhTg', 'U:yRT9YM5BEeWu4gbligZhTg', 'U:yRIXFM5BEeWu4gbligZhTg', 'Data Flow', 'Data Flow', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9YM5BEeWu4gbligZhTg|U:yQQNF85BEeWu4gbligZhTg', 'U:yRT9YM5BEeWu4gbligZhTg', 'U:yQQNF85BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('contains|U:yRT9YM5BEeWu4gbligZhTg|U:yQQ0Qs5BEeWu4gbligZhTg', 'U:yRT9YM5BEeWu4gbligZhTg', 'U:yQQ0Qs5BEeWu4gbligZhTg', 'contains', 'contains', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Validates|U:yRlpiM5BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRlpiM5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Validates', 'Validates', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Validates|U:yRlpiM5BEeWu4gbligZhTg|U:yPh0fs5BEeWu4gbligZhTg', 'U:yRlpiM5BEeWu4gbligZhTg', 'U:yPh0fs5BEeWu4gbligZhTg', 'Validates', 'Validates', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('governedBy|U:yRlpiM5BEeWu4gbligZhTg|U:yRuMX85BEeWu4gbligZhTg', 'U:yRlpiM5BEeWu4gbligZhTg', 'U:yRuMX85BEeWu4gbligZhTg', 'governedBy', 'governedBy', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Validates|U:yRlpic5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRlpic5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'Validates', 'Validates', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Validates|U:yRlpic5BEeWu4gbligZhTg|U:yRT9WM5BEeWu4gbligZhTg', 'U:yRlpic5BEeWu4gbligZhTg', 'U:yRT9WM5BEeWu4gbligZhTg', 'Validates', 'Validates', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('governedBy|U:yRlpic5BEeWu4gbligZhTg|U:yRuMX85BEeWu4gbligZhTg', 'U:yRlpic5BEeWu4gbligZhTg', 'U:yRuMX85BEeWu4gbligZhTg', 'governedBy', 'governedBy', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Validates|U:yRlpis5BEeWu4gbligZhTg|U:yRT9W85BEeWu4gbligZhTg', 'U:yRlpis5BEeWu4gbligZhTg', 'U:yRT9W85BEeWu4gbligZhTg', 'Validates', 'Validates', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Validates|U:yRlpis5BEeWu4gbligZhTg|U:yQQ0Rs5BEeWu4gbligZhTg', 'U:yRlpis5BEeWu4gbligZhTg', 'U:yQQ0Rs5BEeWu4gbligZhTg', 'Validates', 'Validates', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('governedBy|U:yRlpis5BEeWu4gbligZhTg|U:yRuMX85BEeWu4gbligZhTg', 'U:yRlpis5BEeWu4gbligZhTg', 'U:yRuMX85BEeWu4gbligZhTg', 'governedBy', 'governedBy', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('Manages|U:yRuMXM5BEeWu4gbligZhTg|U:yQQNFc5BEeWu4gbligZhTg', 'U:yRuMXM5BEeWu4gbligZhTg', 'U:yQQNFc5BEeWu4gbligZhTg', 'Manages', 'Manages', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yRuMXM5BEeWu4gbligZhTg|U:yRuMXs5BEeWu4gbligZhTg', 'U:yRuMXM5BEeWu4gbligZhTg', 'U:yRuMXs5BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('parent|U:yRuMXc5BEeWu4gbligZhTg|U:yRuMXs5BEeWu4gbligZhTg', 'U:yRuMXc5BEeWu4gbligZhTg', 'U:yRuMXs5BEeWu4gbligZhTg', 'parent', 'parent', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('governedBy|U:yRuMXs5BEeWu4gbligZhTg|U:yRuMW85BEeWu4gbligZhTg', 'U:yRuMXs5BEeWu4gbligZhTg', 'U:yRuMW85BEeWu4gbligZhTg', 'governedBy', 'governedBy', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
Insert into LND_TERM_RELATIONSHIPS
   (JOYFUNCKEY, REL_KEY_TERM_SOURCE, REL_KEY_TERM_TARGET, REL_NAME, REL_DESCRIPTION, 
    JOYLOADDATE, JOYSTATUS)
 Values
   ('governedBy|U:yRuMX85BEeWu4gbligZhTg|U:yRuMW85BEeWu4gbligZhTg', 'U:yRuMX85BEeWu4gbligZhTg', 'U:yRuMW85BEeWu4gbligZhTg', 'governedBy', 'governedBy', 
    TO_TIMESTAMP('02/12/2016 02:24:39.000000','DD/MM/YYYY HH24:MI:SS.FF'), 'L');
COMMIT;
